### ISSUE TITLE
Assignment lifetimes / cloning

### ISSUE THREAD

**Issue by catb0t** [trizen/sidef#51]
I think Sidef doesn't really abuse Perl references for new objects, compare with CPython where you have to tread carefully to keep your object references and identity comparisons bug-free. 

But it does abstract over Perl in the object management area?

Or does it map directly to Perl, where the answer is, "it does whatever Perl would do"?

```ruby
var i = very_large_immediate_iterable # Array, nested Pairs, String, Matrix, Bag (not a RangeNum)
i2 = i     # clone, or take reference and copy on write? 

var h = very_large_hash 
h2 = h     # similar 

var c = BigClass()
c2 = c  # do i have a reference to the object, or a separate copy

f(i, h, c)  # which objects are copied into the next scope and which are a pointer?
```

There are probably other examples I can't think of.

**Comment by catb0t** [comment]
> true for all objects 

except "scalars" like Numbers? `a = 1; b = a; b += 1`  doesn't change `a`, but `a` and `b` are both instances of Number(), and it doesn't change `a` even when `a` is larger than a hardware type and *must* be a GMP bigint.

**Comment by trizen** [comment]
This applies to Number objects also, as illustrated in the following example:

```ruby
var a = 42
var b = a

say (a.refaddr == b.refaddr)    #=> true

a += 1

say a      #=> 43
say b      #=> 42
```

 but the key thing here is that `a += 1` gets compiled to `a = (a + 1)`, which simply makes `a` to point to the object returned by the expression `(a + 1)`, without affecting the object at which `b` is pointing at.

This is because Number objects are immutable (by default). Same for String, File, Dir, Regex and a few others.

However, with a bit of black magic, it's possible to modify `a` in-place, which does affect `b`, but this is really not recommended:

```ruby
var a = 42
var b = a

*a = *(a + 1)

say b       #=> 43
```

**Comment by catb0t** [comment]
I should have thought of that, thanks for the clarification :)
